### ISSUE TITLE
error when run by cpu

### ISSUE THREAD

**Issue by Hugh0120** [XuecaiHu/Meta-SR-Pytorch#11]
When I run main.py with command:
`python main.py --model metardn --save metardn --ext sep --pre_train ./experiment/metardn/model/model_1000.pt --test_only --data_test Set5  --scale 1.5 --cpu`

The following error occurs:

> [1.5]
./benchmark/Set5/HR
./benchmark/Set5/LR_bicubic
5
Making model...
Loading model from ./experiment/metardn/model/model_1000.pt
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    model = model.Model(args, checkpoint)
  File "/Users/junfenghe/Code/Github/Meta-SR-Pytorch/model/__init__.py", line 34, in __init__
    cpu=args.cpu
  File "/Users/junfenghe/Code/Github/Meta-SR-Pytorch/model/__init__.py", line 101, in load
    self.get_model().load_state_dict(
  File "/Users/junfenghe/Code/Github/Meta-SR-Pytorch/model/__init__.py", line 60, in get_model
    return self.model.module
  File "/Users/junfenghe/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'MetaRDN' object has no attribute 'module'

My system is macOS Mojave 10.14.4, python 3.5, and I think my package versions are all correct:

> scikit-image              0.13.1           py35h1de35cc_1    defaults
torch                     0.4.0                    pypi_0    pypi
torchvision               0.2.0                    pypi_0    pypi

**Comment by XuecaiHu** [comment]
I have correct this error. Please update it.
