### ISSUE TITLE
why out of memory?

### ISSUE THREAD

**Issue by Myzhencai** [XuecaiHu/Meta-SR-Pytorch#5]
Hi @XuecaiHu , I have no problem with trainning to get the .pt files with mine own dataset(GPU 1080TI ,ANACONDA3 VIRTUEENV). well , I can not run the test part for reference ,my dataset is combined with 480x270 (low resolution) and 1920x1080(high resolution)
but when I run :    python main.py --model metardn --ext sep  --save metardn --n_GPUs 1 --batch_size 1 --test_only --data_test Set5 --pre_train  ./experiment/metardn/model/minetrained.pt  --save_results --scale 4.0 
I get this error when replace the benchmark file with mine validation files(480x270,1920x1080) as show in image (run with no issue when using the download benchmark files ): 

[4.0]
./benchmark/Set5/HR
./benchmark/Set5/LR_bicubic
1
Making model...
Loading model from ./experiment/metardn/model/model_1000.pt
load_model_mode=1

Evaluation:
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    while not t.terminate():
  File "/home/gaofei/Meta-SR-Pytorch/trainer.py", line 269, in terminate
    self.test()
  File "/home/gaofei/Meta-SR-Pytorch/trainer.py", line 217, in test
    sr = self.model(lr, idx_scale,scale_coord_map)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaofei/Meta-SR-Pytorch/model/__init__.py", line 56, in forward
    return self.model(x,pos_mat)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaofei/Meta-SR-Pytorch/model/metardn.py", line 125, in forward
    local_weight = self.P2W(pos_mat.view(pos_mat.size(1),-1))   ###   (outH*outW, outC*inC*kernel_size*kernel_size)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaofei/Meta-SR-Pytorch/model/metardn.py", line 60, in forward
    output = self.meta_block(x)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/gaofei/anaconda3/envs/metasr/lib/python3.5/site-packages/torch/nn/functional.py", line 992, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

could you please help me out ?

**Comment by XuecaiHu** [comment]
If you want to test our Meta-RDN on very large LR image (Since the RDN is very big model, the size of input image is limtied ), you may need to change the test function in trainer.py by dividing the image into small patches.

**Comment by Myzhencai** [comment]
thank you @XuecaiHu

**Comment by suke27** [comment]
that is excepted, the memory is depend on input size, h*w*inchanel*outchannel*3*3.

**Comment by PonderK** [comment]
I have the same problem, But I don't konw how to divide the image into small patches in trainer.py. Could you please share your code with me? Thanks you very much! @Myzhencai
